### ISSUE TITLE
Virtual list issue when mailbox count exceeds 10

### ISSUE THREAD

**Issue by 2hamed** [postfixadmin/postfixadmin#161] opened 2018-04-16 10:22 UTC
When trying to switch to a domain which its mailbox count exceeds 10, the following error is shown:

> DEBUG INFORMATION:
> Invalid query: no such column: mailbox.username
> 
> Check your error_log for the failed query.
> 
> Please check the documentation and website for more information.

And inside the logs the issue seems to be the following query:

```sql
WITH idx AS (SELECT *  FROM mailbox 
 LEFT JOIN alias ON mailbox.username=alias.address  LEFT JOIN vacation ON mailbox.username=vacation.email 
 WHERE  mailbox.domain='putech.ir' 
 ORDER BY mailbox.username )
                SELECT mailbox.username AS label, (SELECT (COUNT(*) - 1) FROM idx t1 WHERE t1.mailbox.username <= t2.mailbox.username) AS row
                FROM idx t2
                WHERE (row % 10) IN (0,9) OR row = 10;
```

Digging deeper it comes from the `create_page_browser` function inside the functions.php file which is called from `virtual-list.php:426`.

**Update**: The database used is `sqlite`.

**Comment by cboltz** [comment] 2018-04-22 16:43
Looks like the page browser query for sqlite is broken. 

This query is defined in functions.inc.php `function create_page_browser()`, but unfortunately I'm not an expert for sqlite :-(

@phyrog, you contributed the sqlite code two years ago - do you have any idea how to fix this?

Workaround: set `$CONF['page_size'] = '10000';` in your config.local.php so that the page browser doesn't (try to) appear.

**Comment by phyrog** [comment] 2018-04-23 07:04
I think the problem is the table name prefix of `$idxfield`. `t1.mailbox.username` should be `t1.username` and `t2.mailbox.username` should be `t2.username`.

**Comment by DavidGoodwin** [comment] 2019-09-17 20:07
should be fixed

**Closed by DavidGoodwin** 2019-09-17 20:07 UTC
Labels: sqlite
