### ISSUE TITLE
Php 8.1

### ISSUE THREAD

**Issue by zolyyy** [postfixadmin/postfixadmin#632] opened 2022-06-27 09:31 UTC
Hi, 
I use php 8.1 
Too many problems, can't log in... and everything is wrong...

**Comment by DavidGoodwin** [comment] 2022-06-27 10:12
Hello - thanks for the bug report.

What version of Postfixadmin are you trying to use?

**Comment by zolyyy** [comment] 2022-06-27 10:47
Latest 3.3.11

Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/postfixadmin/model/PFASmarty.php on line 137

Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/postfixadmin/model/PFASmarty.php on line 137

Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/postfixadmin/model/PFASmarty.php on line 137

Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/postfixadmin/model/PFASmarty.php on line 137

Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/postfixadmin/model/PFASmarty.php on line 137
Invalid token (session timeout; refresh the page and try again?)

**Comment by DavidGoodwin** [comment] 2022-06-28 09:47
Those Deprecated messages are really an aritfact of your PHP configuration.

You should probably change your php.ini file, and change the 'error_reporting' level to exclude deprecations.

**Comment by DavidGoodwin** [comment] 2022-06-28 09:47
the above commit might help though?

**Comment by zolyyy** [comment] 2022-06-28 10:39
> the above commit might help though?

The error messages have stopped, but I still can't log in. Setup.php finds everything as good.
After try login:
Invalid token (session timeout; refresh the page and try again?)


![image](https://user-images.githubusercontent.com/5923144/176159252-954c8804-7a47-4367-9b2f-49a6580794aa.png)

**Comment by DavidGoodwin** [comment] 2022-06-28 13:55
invalid token - could be caused by ...

 * some problem with cookies to/from your server (e.g. brower is blocking them) or
 * there's something wrong with your server and it's not able to save session files on disk
 * or you have multiple windows/tabs accessing postfixadmin at once (as each new page load would overwrite the session hash value that another depends on).

See also #630

**Comment by zolyyy** [comment] 2022-06-28 19:33
> invalid token - could be caused by ...
> 
> * some problem with cookies to/from your server (e.g. brower is blocking them) or
> * there's something wrong with your server and it's not able to save session files on disk
> * or you have multiple windows/tabs accessing postfixadmin at once (as each new page load would overwrite the session hash value that another depends on).
> 
> See also #630

Cookies, session works. The error message does not disappear. What I noticed in login.php is that the SESSION['PFA_token'] is not created. I am using PHP memcached.

**Comment by DavidGoodwin** [comment] 2022-06-28 19:41
It's possible the error warnings from the PHP8.1 deprecations are being output early in the request, before PHP has started the session / sent cookies. 

I'd suggest you change your php error_reporting level to silence them for now, or tell PHP to log to a file rather than stdout (see  https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-log )

**Comment by ramanzes** [comment] 2022-07-05 16:49
yes, thanks! this solved the problem

**Comment by PowerKiKi** [comment] 2022-07-15 11:39
Is PHP 8.1 officially supported ? Is anybody successfully running postfixadmin on PHP 8.1 ?

**Comment by DavidGoodwin** [comment] 2022-07-15 12:42
@PowerKiKi PHP8.1 should work with the code in 'master'. 

If it doesn't then I'd consider that a bug and something that should be fixed. 

I suspect I'd attempt to back port any fixes to the last stable branch too. Personally I've been a bit lazy and not really used PHP8+ yet (mostly because I'm not yet in $dayjob).

**Closed by DavidGoodwin** 2022-07-15 12:42 UTC
Labels: php

**Comment by andypost** [comment] 2022-07-28 14:37
Please release and Release Candidate to simplify building

**Comment by Nenoni13** [comment] 2022-11-30 13:26
Hello
I've update from php7.4-fpm to php8.1-fpm and I have this Two error :
AH01071: Got error 'PHP message: PHP Warning:  session_start(): Cannot find session save handler &quot;memcache&quot; - session startup failed in /www/html/postfixadmin/common.php on line 25PHP message: PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /www/html/postfixadmin/public/login.php on line 90PHP message: PHP Warning:  session_start(): Cannot find session save handler &quot;memcache&quot; - session startup failed in /www/html/postfixadmin/public/login.php on line 91PHP message: PHP Warning:  Undefined array key "theme_favicon" in /www/html/postfixadmin/templates_c/f28feb935365aa7a3f51e6613c4353d63cac3ffc_0.file.header.tpl.php on line 36'
 AH01071: Got error 'PHP message: PHP Warning:  session_start(): Cannot find session save handler &quot;memcache&quot; - session startup failed in /www/html/postfixadmin/common.php on line 25', referer: https://postfixadmin.nenonipark.tk/login.php

Seens I can't login anymore

Is there any update for postfixadmin for compatibility php8.1 ?

I've rollback to 7.4-fpm to fix the issue

Thx :)

**Comment by DavidGoodwin** [comment] 2022-11-30 14:03
@Nenoni13 I don't think postfixadmin is trying to configure/use a memcache session handler - if you create a "test.php" with : 

```PHP
<?php
session_start();
$_SESSION['test'] = $_SESSION['test'] ?? date('c');
var_dump($_SESSION['test']);

```

and point a browser at it and click refresh a few times, i think you'll see a similar moan/warn about your session handler.

**Comment by DavidGoodwin** [comment] 2022-11-30 20:15
Thanks for confirming

**Comment by supersophie** [comment] 2023-06-29 17:03
HI,

I upgraded from php 7 to php 8.2 and have the same errors.
The installation worked fine until the upgrade to php 8.2
Postfix Version 3.3.13 on Debian 12 and nginx.

 My templates_c is writeable.  
It is mounted via tmpfs  re.g tmpfs			/var/www/mx.exmaple.org/templates_c	tmpfs	nodev,nosuid,noexec,nodiratime,size=4M,uid=33,gid=33,mode=1777   0 0
And www-data can write to this.

The error is: 
2023/06/12 18:51:11 [error] 3799#3799: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/mx989.example.int/functions.inc.php on line 697" while reading response header from upstream, client: 12.24.32.82, server: mx989.example.int, request: "GET /login.php HTTP/2.0", upstream: "[fastcgi://unix:/run/php/php8.2-fpm.sock:](fastcgi://unix/run/php/php8.2-fpm.sock:)", host: "mx989.example.int"
 
   for ($i = 0; $i < $j; ++$i) {
        switch ($string{$i}) {
            case '=':
            case '<':
            case '>':
            case ',':
            case '?':
            case '_':
                if ($iEncStart === false) {
                    $iEncStart = $i;

And the client gets a 403.
Nginx log says: 

==> error.log <==
2023/06/29 17:01:33 [error] 247154#247154: *16103 access forbidden by rule, client: 2.1.1.2, server: mx, request: "GET / HTTP/2.0", host: "mx10.klunky.co.uk"

==> access.log <==
2.1.1.2 - - [29/Jun/2023:17:01:33 +0000] TLSv1.3/TLS_AES_256_GCM_SHA384 "GET / HTTP/2.0" 403 146 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15"

The nginx config did not change.

**Comment by DavidGoodwin** [comment] 2023-06-29 19:13
Thanks for confirming @supersophie
