### ISSUE TITLE
postfix doesn't work after postfixadmind upgrade

### ISSUE THREAD

**Issue by tjano1960** [postfixadmin/postfixadmin#591] opened 2022-01-25 10:31 UTC
Hello!
We run a postfix mail server on Debian 9.
I've upgraded manually from Postfixadmin 3.0.2 (this is the default deb package on Debian 9)
to Postfixadmin 3.8.8
After the upgrade, Postfix started to report errors and doesn't work.
Here is the log:

Jan 24 20:18:04 testmail postfix/proxymap[976]: warning: mysql query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and  (latin1_general_ci,IMPLICIT) for operation '='
Jan 24 20:18:04 testmail postfix/submission/smtpd[975]: warning: proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_domain_maps.cf lookup  error for "tjano1960@gmail.com"
Jan 24 20:18:04 testmail postfix/submission/smtpd[975]: NOQUEUE: reject: RCPT from unknown[192.168.0.50]: 451 4.3.0 <tjano1960@gmail.com

I had to drop "Postfix" Mysql database and import it from a backup. After that Postfix worked again.
I think, Postfixadmin upgrade process changed some tables in the "Postfix" MYsql database, this caused the problem.

Thanks.

**Comment by DavidGoodwin** [comment] 2022-01-25 10:57
Looks like a duplicate of #327 

I think adding this to your public/upgrade.php file may fix it - you might need to change the number so it's only 1 bigger than the last upgrade_xxxx function in the file, and then execute it one way or another (e.g. through a web browser or on the command line should work).

Alternatively, run the SQL manually.


```
function upgrade_1846_mysql()
{
    # See https://github.com/postfixadmin/postfixadmin/issues/327

    $alias = table_by_key('alias');
    $domain = table_by_key('domain');
    $mailbox = table_by_key('mailbox');
    $vacation = table_by_key('vacation');
    $vacation_notification = table_by_key('vacation_notification');
    $alias_domain = table_by_key('alias_domain');
    $domain_admins = table_by_key('domain_admins');

    db_query("ALTER TABLE $alias MODIFY address varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $alias MODIFY goto text  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $alias MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $domain MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $domain MODIFY transport varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $mailbox MODIFY username varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $mailbox MODIFY password varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $mailbox MODIFY maildir varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $mailbox MODIFY local_part varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $mailbox MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $vacation_notification DROP CONSTRAINT vacation_notification_pkey");
    db_query("ALTER TABLE $vacation MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $vacation MODIFY email varchar(255)  COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $alias_domain MODIFY alias_domain varchar(255)  COLLATE latin1_general_ci NOT NULL DEFAULT ''");
    db_query("ALTER TABLE $alias_domain MODIFY target_domain varchar(255)  COLLATE latin1_general_ci NOT NULL DEFAULT ''");

    db_query("ALTER TABLE $vacation_notification MODIFY on_vacation VARCHAR(255) COLLATE latin1_general_ci NOT NULL");
    db_query("ALTER TABLE $vacation_notification ADD CONSTRAINT vacation_notification_pkey FOREIGN KEY (`on_vacation`) REFERENCES $vacation(email) ON DELETE CASCADE");

    db_query("ALTER TABLE $domain_admins MODIFY `domain` varchar(255) COLLATE latin1_general_ci NOT NULL");
}
```

**Comment by tjano1960** [comment] 2022-01-25 16:01
Thank you for your fast reply!

update.php stopped and our MariaDB server displayed an error message at this line :

db_query("ALTER TABLE $vacation_notification DROP CONSTRAINT vacation_notification_pkey");

After some Googling I found that In MySQL, there's no DROP CONSTRAINT , we have to use DROP FOREIGN KEY instead.

I have corrected this line in my update.php. Please correct it on Github too!
After that,  my mysql.log showed that the rest of Mysql commands  were executed succesfully and the database version changed to 1846. Postfix works again!
Thank you!

**Comment by DavidGoodwin** [comment] 2022-01-25 16:56
hm, so is drop constraint a mariadb only thing then?

**Comment by DavidGoodwin** [comment] 2022-01-25 16:57
https://mariadb.com/kb/en/alter-table/#drop-constraint

**Comment by tjano1960** [comment] 2022-01-25 18:45
Our version is: 10.1.48-MariaDB-0+deb9u2 Debian 9.13

**Comment by Aurel035** [comment] 2022-02-11 09:20
Hello,
with postfixadmin version 3.3.10 on debian 11, we see the following intermittent errors in the log, but they are very rare:
Feb 11 08:27:01 mail5 postfix/proxymap[13056]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 08:27:01 mail1 postfix/proxymap[25977]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 08:57:09 mail1 postfix/proxymap[38164]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 08:57:09 mail4 postfix/proxymap[1729]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 09:31:12 mail1 postfix/proxymap[8001]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 09:31:12 mail4 postfix/proxymap[20658]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 10:02:01 mail4 postfix/proxymap[4604]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 10:02:01 mail2 postfix/proxymap[42453]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 10:32:01 mail4 postfix/proxymap[4604]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 10:32:01 mail1 postfix/proxymap[8092]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 11:02:03 mail3 postfix/proxymap[58678]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Feb 11 11:02:03 mail4 postfix/proxymap[53914]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='

**Comment by DavidGoodwin** [comment] 2022-02-11 09:39
@Aurel035 i think you just need the schema updates from https://github.com/postfixadmin/postfixadmin/issues/591#issuecomment-1021061091

**Comment by Aurel035** [comment] 2022-02-11 09:45
Thank you, but will it still work with the current code (3.3.10), after the schema updates?  Or do we have to upgrade postfixadmin as well to the latest version?

**Comment by Aurel035** [comment] 2022-02-11 11:05
After the first 3 queries  we get a lot of errors like the following and we was forced to revert to latin1_swedish_ci:

Feb 11 12:59:38 mail4 postfix/proxymap[48137]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_domain_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '='
Feb 11 12:59:38 mail4 postfix/proxymap[48139]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_domain_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '='
Feb 11 12:59:49 mail1 postfix/proxymap[58712]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_domain_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '='
Feb 11 12:59:49 mail1 postfix/proxymap[58635]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_domain_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '='
Feb 11 12:59:56 mail2 postfix/proxymap[64292]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_domain_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '='
Feb 11 13:00:03 mail3 postfix/proxymap[57837]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_domain_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '='
Feb 11 13:00:05 mail3 postfix/proxymap[49852]: warning: mysql:/etc/postfix/mysql/mysql_virtual_alias_domain_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '=

**Comment by DavidGoodwin** [comment] 2022-02-11 11:20
Yeah - you need to do them all ... not just one or two - the updates above should get all the columns to be the same which should fix everything.

If you want to make the columns all latin1_swedish_ci then fine - but it might break again at some point in the future (e.g. addition of new fields etc).

**Comment by Aurel035** [comment] 2022-02-11 11:27
Now I get this in apache error log, when I click a domain from postfixadmin web interface:

[Fri Feb 11 13:25:06.879012 2022] [php7:notice] [pid 11788] [client 193.151.31.251:40112] Invalid query: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_general_ci,IMPLICIT) and (latin1_swedish_ci,IMPLICIT) for operation '=' caused by SELECT `mailbox`.* , `alias`.goto , `mailbox`.password_expiry as password_expiration , `quota2`.bytes as current \n FROM `mailbox` \n LEFT JOIN `alias` ON `mailbox`.username=`alias`.address  LEFT JOIN `quota2` ON `mailbox`.username=`quota2`.username \n WHERE  `mailbox`.domain= :domain \n ORDER BY `mailbox`.username \n LIMIT 100 OFFSET 0

**Comment by Aurel035** [comment] 2022-02-11 11:53
No, it does the same after running all the queries, the postfix still shows intermittent errors. 
Moreover, we were not able to see the domains from the web interface. 
We had to revert to latin1_swedish_ci

**Comment by DavidGoodwin** [comment] 2022-02-13 09:23
Can I see what you have get from MySQL when you do a  "SHOW CREATE TABLE quota2" please?

**Comment by Aurel035** [comment] 2022-02-13 14:04
Sure, here is the output:

MariaDB [postfix]> SHOW CREATE TABLE quota2;
+--------+-----------------------------------------+
| Table  | Create Table                                                                                                                                                                                                    |
+--------+---------------------------------------+
| quota2 | CREATE TABLE `quota2` (
  `username` varchar(100) NOT NULL,
  `bytes` bigint(20) NOT NULL DEFAULT 0,
  `messages` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`username`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 |
+--------+------------------------------------+
1 row in set (0.000 sec)

**Comment by Aurel035** [comment] 2022-02-14 11:51
Hello,
The following queries seems to resolve the postfix errors, and postfixadmin works fine. Thank you.

ALTER DATABASE postfix DEFAULT COLLATE latin1_general_ci;

alter table admin collate latin1_general_ci;
alter table alias collate latin1_general_ci;
alter table alias_domain collate latin1_general_ci;
alter table config collate latin1_general_ci;
alter table domain collate latin1_general_ci;
alter table domain_admins collate latin1_general_ci;
alter table last_login collate latin1_general_ci;
alter table log collate latin1_general_ci;
alter table mailbox collate latin1_general_ci;
alter table quota collate latin1_general_ci;
alter table quota2 collate latin1_general_ci;


ALTER TABLE postfix.admin MODIFY username varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.admin MODIFY password varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.alias MODIFY address varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.alias MODIFY goto text  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.alias MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.fetchmail MODIFY domain varchar(255)  COLLATE latin1_general_ci NULL DEFAULT '''';
ALTER TABLE postfix.fetchmail MODIFY mailbox varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.fetchmail MODIFY src_server varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.fetchmail MODIFY src_auth enum('password','kerberos_v5','kerberos','kerberos_v4','gssapi','cram-md5','otp','ntlm','msn','ssh','any')  COLLATE latin1_general_ci NULL DEFAULT 'NULL';
ALTER TABLE postfix.fetchmail MODIFY src_user varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.fetchmail MODIFY src_password varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.fetchmail MODIFY src_folder varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.fetchmail MODIFY protocol enum('POP3','IMAP','POP2','ETRN','AUTO')  COLLATE latin1_general_ci NULL DEFAULT 'NULL';
ALTER TABLE postfix.fetchmail MODIFY sslfingerprint varchar(255)  COLLATE latin1_general_ci NULL DEFAULT '''';
ALTER TABLE postfix.fetchmail MODIFY extra_options text  COLLATE latin1_general_ci NULL DEFAULT 'NULL';
ALTER TABLE postfix.fetchmail MODIFY returned_text text  COLLATE latin1_general_ci NULL DEFAULT 'NULL';
ALTER TABLE postfix.fetchmail MODIFY mda varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.alias_domain MODIFY alias_domain varchar(255)  COLLATE latin1_general_ci NOT NULL DEFAULT '''';
ALTER TABLE postfix.alias_domain MODIFY target_domain varchar(255)  COLLATE latin1_general_ci NOT NULL DEFAULT '''';
ALTER TABLE postfix.config MODIFY name varchar(20)  COLLATE latin1_general_ci NOT NULL DEFAULT '''';
ALTER TABLE postfix.config MODIFY value varchar(20)  COLLATE latin1_general_ci NOT NULL DEFAULT '''';
ALTER TABLE postfix.quota2 MODIFY username varchar(100)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.domain MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.domain MODIFY transport varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.quota MODIFY username varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.quota MODIFY path varchar(100)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.vacation MODIFY email varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.vacation MODIFY cache text  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.vacation MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.mailbox MODIFY username varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.mailbox MODIFY password varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.mailbox MODIFY maildir varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.mailbox MODIFY local_part varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.mailbox MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.log MODIFY username varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.log MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.log MODIFY action varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.log MODIFY data text  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.domain_admins MODIFY username varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.domain_admins MODIFY domain varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.vacation_notification MODIFY on_vacation varchar(255)  COLLATE latin1_general_ci NOT NULL;
ALTER TABLE postfix.vacation_notification MODIFY notified varchar(255)  COLLATE latin1_general_ci NOT NULL DEFAULT '''';

**Comment by DavidGoodwin** [comment] 2022-02-14 21:36
Thanks for the long listing above !

**Closed** 2022-02-14 21:43 UTC

**Comment by Aurel035** [comment] 2022-02-18 06:59
The default charset for mysql clients is set to utf8mb4.
