### ISSUE TITLE
BUG: Email-Users cannot change their password

### ISSUE THREAD

**Issue by haegelix** [postfixadmin/postfixadmin#535] opened 2021-08-30 17:13 UTC
OS: Ubuntu 21.04
Postfixadmin Version: 3.3.5
Postfixadmin Installation via Debian Package
Database Server: Maria DB

**My problem:**
Users cannot change their own password. Everytime they try Postfixadmin will throw an exception saying:
`[Mon Aug 30 17:36:31.644040 2021] [php7:notice] [pid 109492] [client XXX.XXX.XXX.XXX:58626] Invalid query: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' caused by UPDATE ``mailbox`` SET  password = :password  WHERE username = :where, referer: https://postfix.jrk-erlangen.de/postfixadmin/users/password.php`

**Why does this happen:**
In /public/users/password.php the function $login->changePassword($username, $fPassword, $fPassword_current) is called.
This will resolve to the file /model/Login.php containing the correct method.
It will call db_update($this->table, 'username', $username, $set), which will resolve to the appropriate method in /functions.inc.php
And this will use a function called table_by_key that is defined in the same document.

But after this chase through the php-Code it so happens, that the table name _mailbox_ got corruptet an looks like this _``mailbox``_ and MariaDB will not accept this as a proper table name. It will instead say, that a table called '' cannot be found.

**What I did to make it work:**
I don't know where the error happens, but to fix it I just commented out some lines in table_by_key($table_key):
```
//    if (db_mysql()) {
//        return "`" . $table . "`";
//    }
```
And now it works just fine. Maybe not the best solution, but it works.

**Comment by DavidGoodwin** [comment] 2021-08-30 20:08
I think this is a duplicate of https://github.com/postfixadmin/postfixadmin/issues/456 - this problem was fixed in the 3.3.8 release.

https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.8

**Closed by DavidGoodwin** 2021-08-30 20:08 UTC
